[package]
name = "liberdus-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version =  "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tiny_http = "0.12.0"
tokio = { version = "1.16.1", features = ["full"] }

